name: Set up self-hosted windows runner on hosted runner

on:
  # Note: invoke workflow_dispatch only between scheduled runs.
  # Otherwise, the workflow may be sent to the wrong configured runner.
  # This caveat will go away once we enable and re-write this workflow to take advantage of ephemeral runners.
  workflow_dispatch:
      
jobs:
  create_runner:
    runs-on: windows-latest
    steps:

      - name: Setup runner and dispatch workflow event
        run: |
          $releases = "https://api.github.com/repos/actions/runner/releases"

          Write-Host Determining latest release

          $assets = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].assets

          $latestVersionWindowsRunnerURL = ($assets | Where-Object { $_.browser_download_url -like "*win*" } | Select -First 1).browser_download_url
          
          Write-Host "Latest version runner Uri for windows : $latestVersionWindowsRunnerURL"
      
          mkdir C:\actions-runner 

          cd C:\actions-runner
          
          Invoke-WebRequest -Uri $latestVersionWindowsRunnerURL -OutFile "runner.zip"

          Add-Type -AssemblyName System.IO.Compression.FileSystem ; 
          [System.IO.Compression.ZipFile]::ExtractToDirectory("$PWD\runner.zip", "$PWD")
          
          
          Write-Host "Get Registration Token"

          $registrationTokenUrl = "https://api.github.com/repos/testorg755/logopu-test/actions/runners/registration-token"

          $headers = @{
           "Content-Type"="application/json"
           "Authorization"= "token 0696a6a832b0144f6dfb39a66658bd7a3fd46add"
          } 

          $registrationToken = ((Invoke-WebRequest -Uri $registrationTokenUrl -Method 'Post' -Headers $headers).Content | ConvertFrom-Json).token
          
          
          Write-Host "Configure runner"

          .\config.cmd --url https://github.com/testorg755/logopu-test --token $registrationToken --name windows-runner --labels canary --unattended --replace #--runasservice

          Start-Process .\run.cmd

          Sleep -Seconds 10
          
          $headers = @{
           "Content-Type"="application/json"
           "Authorization"= "token 0696a6a832b0144f6dfb39a66658bd7a3fd46add"
          } 

          $body = @{
              "ref"="main"
              "inputs"= @{}
          } | ConvertTo-Json


          $dispatchUrl = "https://api.github.com/repos/testorg755/logopu-test/actions/workflows/self-hosted-windows.yml/dispatches"

          Invoke-WebRequest -Uri $dispatchUrl -Method 'Post' -Headers $headers -Body $body

          # sleep for a minute to finish the job
          Start-Sleep 60

          Stop-Process -Name Runner.* -Force

          .\config.cmd remove --token $registrationToken
          
          
          



