name: Set up self-hosted windows runner on hosted runner

on:
  # Note: invoke workflow_dispatch only between scheduled runs.
  # Otherwise, the workflow may be sent to the wrong configured runner.
  # This caveat will go away once we enable and re-write this workflow to take advantage of ephemeral runners.
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
      
jobs:
  create_runner:
    runs-on: windows-latest
    steps:

      - name: Determine latest runner version
        run: |
          $releases = "https://api.github.com/repos/actions/runner/releases"

          Write-Host Determining latest release

          $assets = (Invoke-WebRequest $releases | ConvertFrom-Json)[0].assets

          $latestVersionWindowsRunnerURL = ($assets | Where-Object { $_.browser_download_url -like "*win*" } | Select -First 1).browser_download_url
          
          Write-Host "Latest version runner Uri for windows : $latestVersionWindowsRunnerURL"
          
          [System.Environment]::SetEnvironmentVariable('latestVersionWindowsRunnerURL', $latestVersionWindowsRunnerURL ,[System.EnvironmentVariableTarget]::Machine)
          
      - name: Download runner
        run: |
          Write-Host $env:latestVersionWindowsRunnerURL

