
name: self-hosted-linux

on:
  workflow_dispatch:

jobs:
  basic:
    runs-on: [self-hosted, linux, canary]
    name: linux
    steps:
    - name: OS info
      run: uname -a
    - name: env
      run: env
